version: '3.8'

services:
  mongo-micro:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_saqib
      MONGO_INITDB_ROOT_PASSWORD: devSaqib
    ports:
      - '27017:27017'
    volumes:
      - mongo-micro-data:/data/db

volumes:
  mongo-micro-data: